version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/zyrabit-slm/api-rag"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/zyrabit-slm/web-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
