"""Ports owned by the Zyrabit Node domain."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol, Sequence

from app.node.domain import EvidenceUnit, IngestionJob, Source


class SourceStore(Protocol):
    def persist(self, filename: str, source: Path) -> Source: ...


class DocumentParser(Protocol):
    def parse(self, source: Source, document_id: str) -> Sequence[EvidenceUnit]: ...


class OcrAdapter(Protocol):
    def extract(self, path: str, page: int) -> str: ...


class MetadataStore(Protocol):
    def create_source(self, source: Source) -> None: ...
    def create_document(self, document_id: str, source_id: str, parser: str) -> None: ...
    def set_document_status(self, document_id: str, status: str, error: str | None = None) -> None: ...
    def save_evidence(self, evidence: Sequence[EvidenceUnit]) -> None: ...
    def create_job(self, job: IngestionJob) -> None: ...
    def update_job(self, job_id: str, status: str, stage: str, error: str | None = None, metrics: dict | None = None) -> None: ...
    def get_job(self, job_id: str) -> dict | None: ...
    def get_document(self, document_id: str) -> dict | None: ...
    def search_lexical(self, query: str, limit: int = 8, document_id: str | None = None) -> list[EvidenceUnit]: ...
    def append_message(self, session_id: str, role: str, content: str) -> None: ...
    def get_history(self, session_id: str, limit: int = 8) -> list[dict]: ...
    def clear_history(self, session_id: str) -> None: ...
    def capability(self, name: str, status: str, detail: str = "") -> None: ...
    def capabilities(self) -> list[dict]: ...


class VectorIndex(Protocol):
    def upsert(self, evidence: Sequence[EvidenceUnit]) -> None: ...
    def search(self, query: str, limit: int = 8, document_id: str | None = None) -> list[EvidenceUnit]: ...
    def health(self) -> tuple[bool, str]: ...


class EmbeddingProvider(Protocol):
    def health(self) -> tuple[bool, str]: ...


class RerankerProvider(Protocol):
    def health(self) -> tuple[bool, str]: ...


class InferenceProvider(Protocol):
    def answer(self, prompt: str) -> tuple[str, dict]: ...
    def health(self) -> tuple[bool, str]: ...


class ConversationIdentity(Protocol):
    """Profile data used for voice, never for factual document claims."""
    def current(self) -> dict: ...
