"""
V2.0 Native MCP Bridge: Standardized via official MCP Python SDK.
Includes secure vault importing and resource discovery.
"""

import os
import logging
import shutil
from pathlib import Path

try:
    from mcp.server.fastmcp import FastMCP
except ImportError:
    import unittest.mock as mock
    FastMCP = mock.MagicMock()

from app.infrastructure.shared.config import DOCS_DIR

logger = logging.getLogger("zyrabit.api")

# Initialize FastMCP Server
mcp = FastMCP("Zyrabit Sovereign Core")

@mcp.tool()
async def import_to_vault(source_path: str, destination_name: str) -> str:
    """
    Securely move an external file into the Zyrabit Vault.
    Validates that the file does not contain executable scripts.
    """
    src = Path(source_path)
    if not src.exists():
        return f"Error: Source file {source_path} not found."

    # SECURITY CHECK: Block executable patterns
    try:
        with open(src, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read(10000) # Check first 10k characters
            
            forbidden_patterns = [
                "#!/bin/", "#!/usr/bin/", "os.system(", "subprocess.run(", 
                "<script>", "eval(", "exec(", "import os"
            ]
            
            for pattern in forbidden_patterns:
                if pattern in content:
                    logger.warning(f"🛡️ Security Block: Executable pattern '{pattern}' detected in {source_path}")
                    return f"Security Alert: File {source_path} contains potentially executable code and was rejected."
    except Exception as e:
        return f"Error during security scan: {e}"

    # Move to Vault
    dest_path = Path(DOCS_DIR) / destination_name
    try:
        shutil.copy2(src, dest_path)
        logger.info(f"📥 Vault: Imported {destination_name} successfully.")
        return f"Success: File imported to Vault as {destination_name}"
    except Exception as e:
        return f"Error moving file: {e}"

@mcp.tool()
async def list_vault_stats() -> dict:
    """Returns metadata about the sovereign vault index."""
    try:
        # Placeholder for real stats from SovereignStateManager if needed
        return {"status": "Sovereign Vault is active", "location": DOCS_DIR}
    except Exception as e:
        return {"error": str(e)}

@mcp.tool()
async def send_telegram_notification(message: str) -> str:
    """
    Sends a secure notification to the user's Telegram.
    Intercepts and masks PII via Gatekeeper before transmission.
    """
    from app.domain.services.gatekeeper import Gatekeeper
    
    token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip('"').strip("'")
    chat_id = os.getenv("TELEGRAM_CHAT_ID", "").strip('"').strip("'")
    
    if not token or not chat_id:
        return "Error: Telegram integration not configured. Missing TOKEN or CHAT_ID."
    
    # SECURITY SHIELD: Mask PII before it leaves the sovereign environment
    safe_message, _ = Gatekeeper.mask_pii(message)
    
    import requests
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    try:
        res = requests.post(url, json={
            "chat_id": chat_id,
            "text": f"🛡️ Zyrabit Sovereign Alert:\n\n{safe_message}"
        }, timeout=10)
        
        if res.status_code == 200:
            logger.info("📤 Telegram: Notification sent securely (PII Masked).")
            return "Success: Telegram notification sent (Secure Mode)."
        return f"Error: Telegram API responded with {res.status_code}: {res.text}"
    except Exception as e:
        logger.error(f"❌ Telegram Connection Error: {e}")
        return f"Error connecting to Telegram: {e}"

# Note: The actual Chat logic is still handled by ChatUseCase, 
# but we can expose it as a tool if needed for external clients.
@mcp.tool()
async def secure_query(prompt: str) -> str:
    """Directly query the sovereign SLM via the secure RAG pipeline (PII Masked)."""
    from app.main import _global_app
    try:
        if not _global_app or not hasattr(_global_app.state, 'chat_use_case'):
            return "Error: Chat Use Case is not initialized yet on the FastAPI application."
        chat_use_case = _global_app.state.chat_use_case
        result = await chat_use_case.execute(text=prompt)
        return result.get("response", "Error: No response generated by RAG engine.")
    except Exception as e:
        logger.error(f"❌ MCP secure_query error: {e}")
        return f"Error executing RAG query: {e}"


@mcp.tool()
async def get_quick_start_guide(platform: str = "linux") -> str:
    """
    Get detailed, step-by-step quick start installation guide with commands for the specified platform.
    Args:
        platform: "linux", "mac", or "windows"
    """
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_quick_start_guide(platform)


@mcp.tool()
async def get_api_reference(endpoint: str = "all") -> str:
    """
    Get API Reference guide with curl examples, headers, schemas and response payload models.
    Args:
        endpoint: "chat", "ingest", "health", or "all"
    """
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_api_reference(endpoint)


@mcp.tool()
async def get_docker_compose_example(profile: str = "minimal") -> str:
    """
    Get standard docker-compose.yml templates for Zyrabit SLM deployment.
    Args:
        profile: "minimal" (CPU-only) or "gpu" (NVIDIA GPU acceleration)
    """
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_docker_compose_example(profile)


@mcp.tool()
async def get_architecture_overview() -> str:
    """Get high-level details of Zyrabit's Hexagonal Architecture (Ports, Adapters, Core Domain)."""
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_architecture_overview()


@mcp.tool()
async def get_troubleshooting_guide(error: str) -> str:
    """
    Get detailed step-by-step diagnostic checklist and mitigation commands for common errors.
    Args:
        error: "oom", "memory", "auth", "401", "403" or other error keywords
    """
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_troubleshooting_guide(error)


@mcp.tool()
async def get_environment_variables_reference() -> str:
    """Get the reference documentation table for all available configuration variables in Zyrabit .env."""
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.get_environment_variables_reference()


@mcp.tool()
async def run_self_diagnostic() -> str:
    """Perform real-time self-diagnostics of RAM, CPU, SQLite Database latency, and API Key status."""
    from app.domain.services.documentation_service import DocumentationService
    return DocumentationService.run_self_diagnostic()

@mcp.tool()
async def sync_obsidian_vault() -> str:
    """
    Scans the local Obsidian vault folder and indexes new/modified markdown notes
    dynamically into the hybrid FTS5 and Vector RAG pipeline.
    """
    from app.main import _global_app
    from app.domain.services.obsidian_service import ObsidianService

    try:
        ingest_use_case = _global_app.state.ingest_use_case
        stats = await ObsidianService.sync_vault(ingest_use_case)
        return f"Obsidian Sync Successful! Scanned: {stats['scanned']}, Indexed: {stats['indexed']}, Skipped: {stats['skipped']}, Errors: {stats['errors']}"
    except Exception as e:
        return f"Error executing Obsidian Sync: {e}"


@mcp.tool()
async def generate_reflective_note(session_id: str) -> str:
    """
    Saves a reflective auto-learning summary note of the active session
    directly back into the Obsidian vault folder as a markdown file.
    """
    from app.main import _global_app
    from app.domain.services.obsidian_service import ObsidianService

    try:
        inference_provider = _global_app.state.inference_provider
        result = await ObsidianService.generate_reflective_note(session_id, inference_provider)
        return result
    except Exception as e:
        return f"Error generating reflective note: {e}"


# ---------------------------------------------------------
# DOCKER DIAGNOSTICS MCP (Read-Only)
# ---------------------------------------------------------
from app.infrastructure.mcp.docker_mcp_client import docker_client

@mcp.tool()
async def docker_list_containers() -> str:
    """List all local Docker containers and their status."""
    containers = docker_client.list_containers()
    import json
    return json.dumps(containers, indent=2)

@mcp.tool()
async def docker_get_logs(container_name: str, tail: int = 50) -> str:
    """
    Get the latest logs for a specific Docker container.
    Use this to diagnose failures or check application output.
    """
    return docker_client.get_container_logs(container_name, tail)

@mcp.tool()
async def docker_inspect_container(container_name: str) -> str:
    """
    Inspect a Docker container to see its health, network ports, and restart count.
    """
    info = docker_client.inspect_container(container_name)
    import json
    return json.dumps(info, indent=2)


# LEGACY SHIMS FOR V1.0 COMPATIBILITY
async def handle_jsonrpc(request_dict: dict) -> dict:
    """Legacy shim for V1.0 compatibility."""
    return {"error": "Use V2.0 MCP Bridge via /mcp/rpc"}

def set_mcp_app_state(state):
    """Legacy shim for V1.0 compatibility."""
    pass

