[pytest]
pythonpath = .
testpaths = tests
addopts = -ra -q
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:builtin type SwigPyPacked
    ignore::DeprecationWarning:builtin type SwigPyObject
    ignore::DeprecationWarning:builtin type swigvarlink
